version: '3.8'
services:
  backend:
    container_name: "django-service"
    build: "./djangoapp"
    # environment:
    #   - ENVIRONMENT=production
    volumes:
      - ./volumes/cinema_ticket_backend:/app
      - ./volumes/staticfiles:/app/staticfiles
      - ./volumes/media:/app/media

  nginx:
    container_name: "nginx_proxy"
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/staticfiles:/app/static
      - ./volumes/media:/app/media
    depends_on:
      - backend

    
